### ISSUE TITLE
哥，库里找不到你的发布地址啊

### ISSUE THREAD

**Issue by hegelsu** [zaaach/TopRightMenu#1]
jcenter没找到啊，有上传么？

**Comment by zaaach** [comment]
有上传的啊

**Comment by hegelsu** [comment]
真的找不到。。。
![1](https://cloud.githubusercontent.com/assets/6879123/21739772/fde1734c-d4df-11e6-8c33-04e476022676.png)
> Could not find com.zaaach:toprightmenu:1.0.
     Searched in the following locations:
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.pom
         file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.jar
         https://jcenter.bintray.com/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.pom
         https://jcenter.bintray.com/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.jar
         https://repo1.maven.org/maven2/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.pom
         https://repo1.maven.org/maven2/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.jar
         https://jitpack.io/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.pom
         https://jitpack.io/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.jar
         file:/E:/Develop/Android/android-sdk/extras/android/m2repository/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.pom
         file:/E:/Develop/Android/android-sdk/extras/android/m2repository/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.jar
         file:/E:/Develop/Android/android-sdk/extras/google/m2repository/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.pom
         file:/E:/Develop/Android/android-sdk/extras/google/m2repository/com/zaaach/toprightmenu/1.0/toprightmenu-1.0.jar

**Comment by zaaach** [comment]
我重新上传了一次，等待下啊

**Comment by hegelsu** [comment]
还是没找到。。。

**Comment by zaaach** [comment]
现在可以用了，已经审核过了

**Comment by hegelsu** [comment]
再次试了下，还是下载不下来。。。

**Comment by zaaach** [comment]
那你先下载library手动导入吧，晚会我再看下

**Comment by zaaach** [comment]
这次绝对可以了

**Comment by hegelsu** [comment]
嗯，可以了。
