### ISSUE TITLE
几个问题和需求

### ISSUE THREAD

**Issue by hegelsu** [zaaach/TopRightMenu#3]
1. 业务上遇到这样的情况，右边的菜单的个数是不固定的，且文字长度也是动态从数据库中取的，此时宽度可以自适应，那高度如何自适应
2. 菜单紧贴右边不好看，这个值如何设置好，建议直接给个marginRight的设置会更方便使用
3. 有时候文字内容太少，标题太窄也不好看，一般我会设置最小宽度为屏幕宽度的1/4，如果文字多了则可以自动适应变宽
4. 从图上效果看，左边距太小不好看，是否也可以开放文字左边距的设置
![1](https://cloud.githubusercontent.com/assets/6879123/21774015/0b7f5f94-d6cc-11e6-9e52-602d8fdbcc64.png)

**Comment by zaaach** [comment]
具体业务的实现，你可以下载下来自己修改的嘛~

**Comment by chuanjiangzhou** [comment]
是的，可以下载下来自己修改，我在作者的基础上加了分隔线，背景色，字体颜色.........

**Comment by hegelsu** [comment]
好的。
