### ISSUE TITLE
Model里面加个String类型的参数吧！

### ISSUE THREAD

**Issue by hjj931012** [zaaach/TopRightMenu#9]
一般就是点击后要获取id的啊，而且都是字符串的。虽说可以导入你的model个人感觉还是直接依赖方便些。

**Comment by zaaach** [comment]
你说的id是什么？

**Comment by hjj931012** [comment]
比如说，我点击弹出窗口里面的某一个的时候，需要拿到它对应的id，这个id是赋值的时候就给它了的，因此需要在Model里面加个字符串的参数呗，因为目前你这个Model里面只有两个参数，一个整形的本地图片资源，一个String的标题。如果你把那个整形改为字符串也行。

**Comment by zaaach** [comment]
点击事件回调里可以有当前点击的position

**Comment by zaaach** [comment]
点击事件回调里有当前点击的position

**Comment by hjj931012** [comment]
我晕  说这么多，意思还是没对上啊   private int icon;  private String text;   这是你那Model里面的两个参数
  你就再加一个参数          private String id； 就行了呗！再把set   get 方法加上！

**Comment by zaaach** [comment]
已经更新了
